import {
  SHOPPING_ITEM_CATEGORIES,
  SHOPPING_ITEM_UNITS,
  type ShoppingItemCategory,
} from "@/types/shopping-list";

export const DEFAULT_LIST_PARSER_MODEL = "gpt-4.1-mini";

export const SHOPPING_UNITS = SHOPPING_ITEM_UNITS;

export const CATEGORY_KEYWORDS: Record<ShoppingItemCategory, string[]> = {
  produce: [
    "apple",
    "banana",
    "bananas",
    "maçã",
    "maca",
    "manzana",
    "plátano",
    "platano",
    "lettuce",
    "tomato",
    "tomate",
    "potato",
    "onion",
    "carrot",
    "orange",
    "broccoli",
    "spinach",
    "pepper",
    "cucumber",
  ],
  dairy: [
    "milk",
    "leite",
    "leche",
    "egg",
    "eggs",
    "ovo",
    "ovos",
    "huevo",
    "huevos",
    "cheese",
    "queijo",
    "queso",
    "yogurt",
    "iogurte",
    "yogur",
    "butter",
    "manteiga",
    "mantequilla",
    "cream",
    "mozzarella",
  ],
  meat: [
    "chicken",
    "frango",
    "pollo",
    "beef",
    "carne",
    "fish",
    "peixe",
    "pescado",
    "salmon",
    "tuna",
    "tofu",
    "ham",
    "turkey",
    "bacon",
  ],
  bakery: [
    "bread",
    "pão",
    "pao",
    "pan",
    "bagel",
    "bun",
    "croissant",
    "wrap",
    "tortilla",
    "cake",
  ],
  pantry: [
    "rice",
    "arroz",
    "pasta",
    "flour",
    "farinha",
    "harina",
    "salt",
    "sal",
    "sugar",
    "açúcar",
    "acucar",
    "azúcar",
    "azucar",
    "beans",
    "feijão",
    "feijao",
    "frijol",
    "lentil",
    "cereal",
    "oil",
    "olive oil",
    "azeite",
    "aceite",
    "vinegar",
    "sauce",
    "spice",
  ],
  frozen: ["frozen", "ice cream", "pizza", "fries"],
  beverages: [
    "water",
    "água",
    "agua",
    "juice",
    "sumo",
    "zumo",
    "soda",
    "coffee",
    "café",
    "cafe",
    "tea",
    "chá",
    "cha",
    "té",
  ],
  cleaning: [
    "detergent",
    "detergente",
    "soap",
    "sabão",
    "sabao",
    "jabón",
    "jabon",
    "cleaner",
    "bleach",
  ],
  "personal-care": ["shampoo", "toothpaste", "deodorant", "lotion"],
  household: [
    "paper towel",
    "toilet paper",
    "papel higienico",
    "papel higiénico",
    "trash bag",
    "bin bag",
  ],
  other: [],
};

export function getAllowedCategories() {
  return [...SHOPPING_ITEM_CATEGORIES];
}
